name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      # - name: Set code coverage commit status
      #   run: npx set-gh-status

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Add Codecov token to GitHub secrets
          files: ./coverage/lcov.info
          flags: unittests
          name: code-coverage-report
